# Generated by Django 6.0.3 on 2026-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=20, verbose_name='Centro')),
                ('centro_beneficio', models.CharField(max_length=50, verbose_name='C. Beneficio')),
                ('pssr', models.CharField(max_length=100, verbose_name='PSSR / Asesor')),
                ('pedido', models.BigIntegerField(unique=True, verbose_name='Pedido')),
                ('factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('tipo_doc', models.CharField(max_length=20, verbose_name='Tipo Doc')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad / Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Doc')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('venta_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margen_porcentaje', models.FloatField(verbose_name='Margen %')),
                ('repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('terceros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
