# Generated by Django 6.0.3 on 2026-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Cliente', models.TextField(db_column='Cliente')),
                ('Factura', models.TextField(db_column='Factura')),
                ('Tipo_Facturacion', models.TextField(db_column='Tipo_Facturacion')),
                ('PSSR', models.TextField(db_column='PSSR')),
                ('Fecha_Facturacion', models.DateField(blank=True, db_column='Fecha_Facturacion', null=True)),
                ('ESTADO', models.TextField(db_column='ESTADO')),
                ('Fecha_Seguimiento', models.DateField(blank=True, db_column='Fecha_Seguimiento', null=True)),
                ('Tipo_Contacto', models.TextField(blank=True, db_column='Tipo_Contacto', null=True)),
                ('Observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
            ],
            options={
                'db_table': 'Seguimiento',
                'managed': True,
            },
        ),
    ]
